#!/usr/bin python
# -*- coding: utf-8 -*-

#srieck 9.22.2023
# test_venv\Scripts\activate.bat

#libs, mods, pkgs
from sqlite3.dbapi2 import InterfaceError
import pandas as pd
from pandas.core import indexing
from pandas.core.indexes.base import Index
import numpy as np
from pathlib import Path
import openpyxl
import sqlite3
import redshift_connector
from datetime import datetime
import os
import glob 
from timeit import default_timer as timer
import time
from datetime import datetime
import config

# Redshift Connection Details 
class getCred():
    def __init__(self, ENV_NAME=None, USER_NAME=None):
        self.ENV_NAME = ENV_NAME
        self.USER_NAME = USER_NAME

    def getHost(self):
        if self.ENV_NAME=='dev':
            HOST_NAME='cfsan-dw-db.dev.fda.gov'
        elif self.ENV_NAME=='preprod': 
            HOST_NAME='cfsan-dw-db.preprod.fda.gov' 
        else: 
            self.ENV_NAME=='prod'
            HOST_NAME='cfsan-dw-db.fda.gov'   
        return HOST_NAME

    def getPw(self):
        if self.ENV_NAME=='dev':
            pw=config.DEV_PASSWORD 
        elif self.ENV_NAME=='preprod':
            pw=config.PREPROD_PASSWORD
        else: 
            self.ENV_NAME=='prod'
            pw=config.PROD_PASSWORD
        return pw   


schema = config.SCHEMA_NAME
today=datetime.today().strftime('%Y.%m.%d')
mapping_file = config.MAP_FILE_NAME
conn = sqlite3.connect('temp_database.db')
mapDF = pd.read_excel(mapping_file, sheet_name=config.MAP_SHEET_NAME, engine='openpyxl')
data = []
data1 = []


def modFile():
    cwd = os.getcwd()
    # if config.STORED_PROCEDURE_FILE is not None:
    #     listing = os.listdir(cwd)
    #     for infile in listing:
    #         print(os.path.splitext(infile)[0])
    # else:
    #     pass

    with open(
        'IMS_StoredProcedure.txt', 'r') as r, open(
            'IMS_StoredProcedure2.txt', 'w') as o:

        for line in r:
            if line.strip():
                o.write(line.lower())
            if " ".join(line.split()):
                o.write(line.lower())    

        f = open(config.STORED_PROCEDURE_FILE)
        contents = f.read()
        print(contents)
        f.close()
        new_contents = contents.replace('(', ',').replace('(', '\n').replace('except', 'start').replace('AND cdw_created_timestamp IS NULL 	;', 'end').replace('SET cdw_created_timestamp = CURRENT_TIMESTAMP ', 'end').replace('WHERE 1 = 1 ', '').replace('	', '').replace(')', '\n').replace(';', '').replace('SELECT', ', SELECT').replace('FROM', ', FROM').replace('UPDATE', ', UPDATE').replace('where 1 = 1', '')
        f = open('.txt', 'w')
        f.write(new_contents)
        f.close()
        df = pd.read_csv(r'.txt', low_memory=True, header=None, names=['SQL'], sep='\n', engine='python')
        df.to_excel("dV1_{}_{}.xlsx".format(schema, today), encoding='utf-8', engine='openpyxl')
        df['C'] = np.arange(len(df))
        df = pd.DataFrame(data=df)
        return df 

d = modFile()
d.to_excel("d.xlsx".format(schema, today), encoding='utf-8', engine='openpyxl')
print(modFile)

data = d['SQL']
df = pd.DataFrame(data)
print(df)
flag = False
df2 = df.copy()


for i, j in df.iterrows():
    if j['SQL'] == 'start':
        flag = True
        df2 = df2.drop(df.index[[i]])
        print(df2)
    elif j['SQL'] =='end':
        flag = False
        df2 = df2.drop(df.index[[i]])
    elif flag:
        df2 = df2.drop(df.index[[i]])

print(df2)
df2.to_excel("letsgo.xlsx".format(schema, today), encoding='utf-8', engine='openpyxl')


# df = pd.DataFrame({'c2': ['1', 'start', '3', 'end','5','start','end', '1', 'start', '3', 'end','5','start','end',0]})
# df2 = df.copy()
# flag = False
# for i, j in df.iterrows():
#     if j['c2'] == 'start':
#         flag = True
#         df2 = df2.drop(df.index[[i]])
#     elif j['c2'] =='end':
#         flag = False
#         df2 = df2.drop(df.index[[i]])
#     elif flag:
#         df2 = df2.drop(df.index[[i]])

# print(df2)


#df = pd.read_excel('dV1_milk_2024.05.07.xlsx', sheet_name='Sheet1', engine='openpyxl')
# df['SQL'] = df['SQL'].apply(lambda x: x.strip())
# print(df)
#df.to_excel("dV1_{}_{}.xlsx".format(schema, today), encoding='utf-8', engine='openpyxl')



# outcome = (df.set_axis(['SQL'], axis = 1)
#              .assign(Validation_Error_Information = lambda df: df['Validation_Error_Information'].str.split(" < "))
#              .explode('Validation_Error_Information')
#              .agg(" < ".join, axis = 1) #.reset_index()
#             )
#print(outcome)


# queries = pd.read_sql("""
#                     with k as (Select 
#                         [Source Table Name],
#                         [Source Column Name],
#                         [Target Table Name],
#                         case when [Target Nullable] like 'N%' then [Target Column Name]
#                             else null 
#                             end as primarykeys2,  
#                         case when [Source Nullable] like 'N%' then [Source Table Name] || '.' || [Source Column Name]
#                             else null 
#                             end as primarykeys1,    
#                         [Target Nullable]
#                     from mapping) 
#                     , J AS (select distinct row_number() over(Partition By k.[Source Table Name]) as rn,
#                         k.[Target Table Name],
#                         k.[Source Table Name],
#                         'select count(*) as Landing_Results from landing.{}.' || lower(k.[Source Table Name]) || ' ; ' as stQuery,
#                         'select count(*) as Cierra_Results from ceirra.cdw_facility.' || lower(k.[Target Table Name]) || ' ;' as ttQuery
#                     from k
#                     --join q on lower(k.[Target Table Name]) = lower(q.[Target Table Name])
#                       )
#                    select * from j 
#                    where ttQuery is not null and rn = 1

#                 """.format(schema), conn)


# #########################################################################################################################33

# querySQL = """ with t as (select distinct
#             mapping.[Target Table Name] from mapping)
#             , q as (select ttQuery as Target_Query,
#             case when stQuery like '%,%' then replace(stQuery, ';', '(+) ;') else stQuery end as Source_Query
#             from queries )
#             select * from q left join t on q.Target_Query like '%'+ t.[Target Table Name] +'%'
#             where Source_Query is not null; """.format(schema)
            
# def genQuery():    
#     df = modFile()
#     df = pd.DataFrame(data=df)
#     df.to_sql('data', conn, if_exists='replace') 
#     mapDF.to_sql('mapping', conn, if_exists='replace') 
#     queries.to_sql('queries', conn, if_exists='replace') 
#     generateQuery = pd.read_sql(querySQL, conn)
#     print(generateQuery)
#     generateQuery.to_excel("generateQuery.xlsx".format(schema, today), encoding='utf-8', engine='openpyxl')
#     return generateQuery


# def TargetCon(): 
#     if config.TARGET_DATABASE == 'ceirra':
#         cred = getCred(config.ENV_NAME, config.USER_NAME)
#         ceirraConn = redshift_connector.connect(
#             host=cred.getHost(),
#             database=config.TARGET_DATABASE,
#             port=443,
#             user=cred.USER_NAME,
#             password=cred.getPw(),    
#             ssl=True)            
#         cursor_ceirra = ceirraConn.cursor()

#         generateQuery = genQuery()
#         data1 = pd.DataFrame(columns = ["Ceirra Results"])
#         n = {'Ceirra Results': ['n']}
#         ndata = pd.DataFrame(data=n)
#         for i in range(0, len(generateQuery)):
#             v = generateQuery['Target_Query'].iloc[i]
#             targetSQL = """ {} """.format(v)
#             #print(targetSQL)
#             cursor_ceirra.execute(targetSQL)       
#             result1 = pd.DataFrame(cursor_ceirra.fetch_dataframe())
#             data1 = data1.append(result1)
#             #print(data1)
#         cursor_ceirra.close  
#         ceirraConn.close  
#         return data1


# def LandingCon(): 
#     if config.SOURCE_DATABASE == 'landing':
#         cred = getCred(config.ENV_NAME, config.USER_NAME)
#         landingConn = redshift_connector.connect(
#             host=cred.getHost(),
#             database=config.TARGET_DATABASE,
#             port=443,
#             user=cred.USER_NAME,
#             password=cred.getPw(),  
#             ssl=True)            
#         cursor_landing = landingConn.cursor()

#         generateQuery = genQuery()
#         data = pd.DataFrame(columns = ["Landing Results"])
#         n = {'Landing Results': ['n']}
#         ndata = pd.DataFrame(data=n)
#         for i in range(0, len(generateQuery)):
#             v = generateQuery['Source_Query'].iloc[i]
#             sourceSQL = """ {} """.format(v)
#             cursor_landing.execute(sourceSQL)       
#             if timer == 5.0000000:            
#                 #print("{} ran too long and was skipped".format(sourceSQL))
#                 result = ndata
#                 pass

#             result = pd.DataFrame(cursor_landing.fetch_dataframe())
#             data = data.append(result)
#         cursor_landing.close    
#         landingConn.close
#         return data
   

# def formatResults():
#     df1 = genQuery()
#     df1.reset_index(inplace=True)
#     # print(df1)
#     # df1.to_excel("dV1_{}_{}.xlsx".format(schema, today), encoding='utf-8', engine='openpyxl')
#     df2 = TargetCon()
#     df2.reset_index(inplace=True)
#     # df2.to_excel("dV2_{}_{}.xlsx".format(schema, today), encoding='utf-8', engine='openpyxl')
#     df3 = LandingCon()
#     df3.reset_index(inplace=True)
#     #df3.to_excel("dV3_{}_{}.xlsx".format(schema, today), encoding='utf-8', engine='openpyxl')
#     #frames = [df1.reset_index(drop=True), df2.reset_index(drop=True), df3.reset_index(drop=True)]
#     dataValidationRESULTS = pd.concat([df1.reset_index(drop=True), df2.reset_index(drop=True), df3.reset_index(drop=True)], ignore_index=False, axis=1)
#     dataValidationRESULTS.to_excel("Denormalized_Counts_RESULTS_{}_{}.xlsx".format(schema, today), index=None, encoding='utf-8', engine='openpyxl')




# if __name__ == '__main__':
#     try: formatResults()
#     except Exception as e:
#         print(e) 
#     else: 
#         print("Data Counts Concluded Without Error on {}!".format(today))
        
        

